services:
  - type: web
    name: nasaansidimla
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false